"use strict";
// Bundle local CommonJS modules without npm dependencies. External Node/Obsidian modules stay external.
const fs = require("fs"), path = require("path");
function build(destination = path.join(__dirname, "dist")) {
  const names = ["main", "core", "audio", "services", "images", "../farore-scene-illustrator/core"];
  const definitions = names.map(name => `${JSON.stringify(name.startsWith("..") ? name : `./${name}`)}: function(module, exports, require) {\n${fs.readFileSync(path.join(__dirname, `${name}.js`), "utf8")}\n}`).join(",\n");
  const bundle = `"use strict";\n// Generated by build.js; edit the maintained source files.\nconst __nativeRequire = require;\nconst __modules = {\n${definitions}\n};\nconst __cache = {};\nfunction __load(id) {\n  if (!__modules[id]) return __nativeRequire(id);\n  if (__cache[id]) return __cache[id].exports;\n  const m = { exports: {} }; __cache[id] = m;\n  __modules[id](m, m.exports, __load); return m.exports;\n}\nmodule.exports = __load("./main");\n`;
  fs.mkdirSync(destination, { recursive: true }); fs.writeFileSync(path.join(destination, "main.js"), bundle);
  for (const file of ["manifest.json", "styles.css"]) fs.copyFileSync(path.join(__dirname, file), path.join(destination, file));
  return destination;
}
if (require.main === module) console.log(build());
module.exports = { build };
